[workspace]
members = ["e2e-identity", "jwt", "ffi", "cli", "acme"]
resolver = "2"

[patch.crates-io.biscuit]
git = "https://github.com/beltram/biscuit"
branch = "feat/wasm"

[patch.crates-io.jwt-simple]
git = "https://github.com/beltram/rust-jwt-simple"
branch = "wire"

[patch.crates-io.rcgen]
git = "https://github.com/wireapp/rcgen"
tag = "v1.1.0-pre.core-crypto-0.6.0"
